/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5JFp4hBddqScvsM8xAASW5

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsd2ZtgqihBnir } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: d2ztgqihBnir/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsd2ZtgqihBnir
});
